### ISSUE TITLE
Auto Hammer Crash

### ISSUE THREAD

**Issue by InkDragon** [MikeLydeamore/Ex-Astris#40] opened 2015-03-04 00:28 UTC
http://paste.ee/p/YkjZM

I attempted to put some cobble into the auto hammer, and I received this crash.

Using the latest ex-astris from the jenkins and version 1.37 of ex nihilo(due to the latest version from the jenkins causing a crash.)

**Comment by MikeLydeamore** [comment] 2015-03-04 00:39
This is because you are not using an up to date version of Ex Nihilo. What crash are you getting while using that?

**Comment by InkDragon** [comment] 2015-03-04 01:04
http://paste.ee/p/CoxnW
This would be the crash I receive when using the latest version of ex Nihilo from the jenkins

**Comment by MikeLydeamore** [comment] 2015-03-05 05:22
Can you try updating to the newest versions on CurseForge and see if this issue persists?

**Comment by InkDragon** [comment] 2015-03-05 05:27
http://paste.ee/p/t9pMH

This is with both the newest versions of Ex Nihilo and Ex Astris from curse

**Comment by MikeLydeamore** [comment] 2015-03-05 05:35
Your crash log seems to be getting cut off, can you maybe upload to a different website so I can check the whole thing?

**Comment by InkDragon** [comment] 2015-03-05 05:55
http://pastebin.com/T1CTHKdk
try that

**Comment by MikeLydeamore** [comment] 2015-03-06 06:02
This *might* be fixed with the newest Ex Nihilo. I'm still unable to reproduce this, but I think it's because another mod is registering oreIron with something that isn't a block.

**Comment by InkDragon** [comment] 2015-03-06 06:18
that would likely be this mod: https://github.com/DemoXinMC/FortuneOres

I know back in 1.6.4 versions there was an issue caused by Fortune Ores having issues with the hammers. I thought DemoXin had fixed it on his end

**Comment by MikeLydeamore** [comment] 2015-03-06 06:19
Worth updating to the newest versions (of both Nihilo and Astris) to see if the issue is fixed. If not, I'll keep poking at it.

**Comment by InkDragon** [comment] 2015-03-06 06:40
Since you pointed it to possibly being fortune ores, I went a head and pulled all the other mods out and what do yah know, boom crash.

Here is the crashlog: http://pastebin.com/DsgFdMuk

Only mods installed are ex nihilo, ex astris and fortune ores. All are the latest versions.

Something broke between v1.37 of ex nihilo and v1.38 as prior to v1.38 there was no issue. Not sure if that info is helpful or not

**Comment by MikeLydeamore** [comment] 2015-03-06 08:14
OK, now we've tracked down the mod, I've been able to test directly against it. It should be fixed in the newest Ex Nihilo (http://ci.tterrag.com/job/Ex-Nihilo/19/). I am able to successfully launch with FortuneOres and also Ex Astris/Nihilo in place. Thanks for being very helpful and very patient.

Feel free to re-open if the issue persists.

**Closed by MikeLydeamore** 2015-03-06 08:14 UTC
Labels: Needs Confirming

**Comment by InkDragon** [comment] 2015-03-06 08:20
thank you <3 once again works 100% fine with fortune ores
