### ISSUE TITLE
New Thermal Foundation and Thermal Dynamics conflict.

### ISSUE THREAD

**Issue by JoeSchmo2840** [MikeLydeamore/Ex-Astris#33] opened 2015-02-23 05:07 UTC
cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: thermalfoundation/entity/monster/EntityBlizz
[B#272]  	at cpw.mods.fml.common.LoadController.transition(LoadController.java:162)
[B#272]  	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:695)
[B#272]  	at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:288)
[B#272]  	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:541)
[B#272]  	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867)
[B#272]  	at net.minecraft.client.main.Main.main(SourceFile:148)
[B#272]  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[B#272]  	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[B#272]  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[B#272]  	at java.lang.reflect.Method.invoke(Unknown Source)
[B#272]  	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[B#272]  	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[B#272]  Caused by: java.lang.NoClassDefFoundError: thermalfoundation/entity/monster/EntityBlizz
[B#272]  	at ExAstris.ExAstris.PostInitialize(ExAstris.java:80)
[B#272]  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[B#272]  	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[B#272]  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[B#272]  	at java.lang.reflect.Method.invoke(Unknown Source)
[B#272]  	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:513)
[B#272]  	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
[B#272]  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[B#272]  	at java.lang.reflect.Method.invoke(Unknown Source)
[B#272]  	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
[B#272]  	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
[B#272]  	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
[B#272]  	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
[B#272]  	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
[B#272]  	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
[B#272]  	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
[B#272]  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[B#272]  	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[B#272]  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[B#272]  	at java.lang.reflect.Method.invoke(Unknown Source)
[B#272]  	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
[B#272]  	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
[B#272]  	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
[B#272]  	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
[B#272]  	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
[B#272]  	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
[B#272]  	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:694)
[B#272]  	... 10 more
[B#272]  Caused by: java.lang.ClassNotFoundException: thermalfoundation.entity.monster.EntityBlizz
[B#272]  	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
[B#272]  	at java.lang.ClassLoader.loadClass(Unknown Source)
[B#272]  	at java.lang.ClassLoader.loadClass(Unknown Source)
[B#272]  	... 37 more
[B#272]  Caused by: java.lang.NullPointerException
[B#272]

**Comment by MikeLydeamore** [comment] 2015-02-23 05:13
Duplicate of #32, #31, #30, #25 and #23.

Please get the new builds from the Jenkins:
http://ci.tterrag.com/job/Ex-Astris/
and
http://ci.tterrag.com/job/Ex-Nihilo/

**Comment by JoeSchmo2840** [comment] 2015-02-23 05:25
Sorry for the dupes. And thanks for the information. I will update now

**Comment by MikeLydeamore** [comment] 2015-03-05 05:23
Gonna close this now the new builds are out on CurseForge.

**Closed by MikeLydeamore** 2015-03-05 05:23 UTC
