### ISSUE TITLE
Tinkers Construct compatibility issue

### ISSUE THREAD

**Issue by Zsashas** [MikeLydeamore/Ex-Astris#15] opened 2015-01-27 02:17 UTC
I asked about this on the other github before seeing that it was moved to here.

When placing Traveller's armor in the Crafting Station, Tool Station, or Tool Forge, then adding one of the items used for modifiers, such as lily pads, it crashes and deletes the modifier item. The armor is apparently dropped on the ground outside the table. The crash report mentions something about the Crooked modifier. Here's a crash report:

http://pastebin.com/5d5fnMvN

**Comment by MikeLydeamore** [comment] 2015-01-27 02:27
Duplicate of #9. Fixed in e0c4b0c8727fc3bf7ae15c11ee8c68ce9730c5b1 and in Release 1.15.

**Closed by MikeLydeamore** 2015-01-27 02:27 UTC
